'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OPT.OrionP.OrionCopL.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de adicionar módulos de contribucion al servicio, es necesario que el servicio este en modo de &apos;Modificación&apos;´..
        '''</summary>
        Friend ReadOnly Property AdicionarModulosModificando() As String
            Get
                Return ResourceManager.GetString("AdicionarModulosModificando", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INFORMACION: Aún hay campos requeridos por satisfacer!.
        '''</summary>
        Friend ReadOnly Property CamposSinSatisfacer() As String
            Get
                Return ResourceManager.GetString("CamposSinSatisfacer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.
        '''</summary>
        Friend ReadOnly Property Cero() As String
            Get
                Return ResourceManager.GetString("Cero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ,.
        '''</summary>
        Friend ReadOnly Property Coma() As String
            Get
                Return ResourceManager.GetString("Coma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Valor del Período mayor al Saldo!.
        '''</summary>
        Friend ReadOnly Property errPeriodoMayorSaldo() As String
            Get
                Return ResourceManager.GetString("errPeriodoMayorSaldo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contingencia.
        '''</summary>
        Friend ReadOnly Property MFContingencia() As String
            Get
                Return ResourceManager.GetString("MFContingencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Importada.
        '''</summary>
        Friend ReadOnly Property MFImportada() As String
            Get
                Return ResourceManager.GetString("MFImportada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Manual.
        '''</summary>
        Friend ReadOnly Property MFManual() As String
            Get
                Return ResourceManager.GetString("MFManual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sistema.
        '''</summary>
        Friend ReadOnly Property MFSistema() As String
            Get
                Return ResourceManager.GetString("MFSistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Anticipo aplicado a Capital.
        '''</summary>
        Friend ReadOnly Property NAAAntAplCap() As String
            Get
                Return ResourceManager.GetString("NAAAntAplCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Anticipo aplicado a Intereses.
        '''</summary>
        Friend ReadOnly Property NAAAntAplInt() As String
            Get
                Return ResourceManager.GetString("NAAAntAplInt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descuento Pronto Pago Aplicado.
        '''</summary>
        Friend ReadOnly Property NAADsctoPP() As String
            Get
                Return ResourceManager.GetString("NAADsctoPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Anticipo aplicado a Capital.
        '''</summary>
        Friend ReadOnly Property NAARAntAplCap() As String
            Get
                Return ResourceManager.GetString("NAARAntAplCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Anticipo aplicado a Intereses.
        '''</summary>
        Friend ReadOnly Property NAARAntAplInt() As String
            Get
                Return ResourceManager.GetString("NAARAntAplInt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversion Descuento Pronto Pago Aplicado.
        '''</summary>
        Friend ReadOnly Property NAARDsctoPP() As String
            Get
                Return ResourceManager.GetString("NAARDsctoPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención en la Fuente Aplicado.
        '''</summary>
        Friend ReadOnly Property NAAReteFte() As String
            Get
                Return ResourceManager.GetString("NAAReteFte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención Industria y Comercio Aplicado.
        '''</summary>
        Friend ReadOnly Property NAAReteIca() As String
            Get
                Return ResourceManager.GetString("NAAReteIca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención del IVA Aplicado.
        '''</summary>
        Friend ReadOnly Property NAAReteIva() As String
            Get
                Return ResourceManager.GetString("NAAReteIva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Retención en la Fuente Aplicado.
        '''</summary>
        Friend ReadOnly Property NAARReteFte() As String
            Get
                Return ResourceManager.GetString("NAARReteFte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención Industria y Comercio Reversado.
        '''</summary>
        Friend ReadOnly Property NAARReteIca() As String
            Get
                Return ResourceManager.GetString("NAARReteIca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención del IVA Reversado.
        '''</summary>
        Friend ReadOnly Property NAARReteIva() As String
            Get
                Return ResourceManager.GetString("NAARReteIva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;Ninguno&gt;.
        '''</summary>
        Friend ReadOnly Property Ninguno() As String
            Get
                Return ResourceManager.GetString("Ninguno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a OriPBk.
        '''</summary>
        Friend ReadOnly Property NombreBk() As String
            Get
                Return ResourceManager.GetString("NombreBk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pago aplicado a Capital.
        '''</summary>
        Friend ReadOnly Property RCAbonoCap() As String
            Get
                Return ResourceManager.GetString("RCAbonoCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pago aplicado a Intereses de Mora.
        '''</summary>
        Friend ReadOnly Property RCAbonoMor() As String
            Get
                Return ResourceManager.GetString("RCAbonoMor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Anticipo recibido.
        '''</summary>
        Friend ReadOnly Property RCAnticipo() As String
            Get
                Return ResourceManager.GetString("RCAnticipo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Anticipo recibido.
        '''</summary>
        Friend ReadOnly Property RCAntRec() As String
            Get
                Return ResourceManager.GetString("RCAntRec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descuento a Capital.
        '''</summary>
        Friend ReadOnly Property RCDsctoCap() As String
            Get
                Return ResourceManager.GetString("RCDsctoCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descuento a Intereses de Mora.
        '''</summary>
        Friend ReadOnly Property RCDsctoMor() As String
            Get
                Return ResourceManager.GetString("RCDsctoMor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descuento por Pronto Pago.
        '''</summary>
        Friend ReadOnly Property RCDsctoPP() As String
            Get
                Return ResourceManager.GetString("RCDsctoPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Pago a Capital.
        '''</summary>
        Friend ReadOnly Property RCRAbonoCap() As String
            Get
                Return ResourceManager.GetString("RCRAbonoCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Pago Intereses Mora.
        '''</summary>
        Friend ReadOnly Property RCRAbonoMor() As String
            Get
                Return ResourceManager.GetString("RCRAbonoMor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Anticipo recibido.
        '''</summary>
        Friend ReadOnly Property RCRAnticipo() As String
            Get
                Return ResourceManager.GetString("RCRAnticipo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Anticipo recibido.
        '''</summary>
        Friend ReadOnly Property RCRAntRec() As String
            Get
                Return ResourceManager.GetString("RCRAntRec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Descuento a Capital.
        '''</summary>
        Friend ReadOnly Property RCRDsctoCap() As String
            Get
                Return ResourceManager.GetString("RCRDsctoCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Descuento Intereses de Mora.
        '''</summary>
        Friend ReadOnly Property RCRDsctoMor() As String
            Get
                Return ResourceManager.GetString("RCRDsctoMor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Descuento Pronto Pago.
        '''</summary>
        Friend ReadOnly Property RCRDsctoPP() As String
            Get
                Return ResourceManager.GetString("RCRDsctoPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención en la Fuente.
        '''</summary>
        Friend ReadOnly Property RCReteFte() As String
            Get
                Return ResourceManager.GetString("RCReteFte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención de Industria y Comercio.
        '''</summary>
        Friend ReadOnly Property RCRetIca() As String
            Get
                Return ResourceManager.GetString("RCRetIca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención del IVA.
        '''</summary>
        Friend ReadOnly Property RCRetIva() As String
            Get
                Return ResourceManager.GetString("RCRetIva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Retención en la Fuente.
        '''</summary>
        Friend ReadOnly Property RCRReteFte() As String
            Get
                Return ResourceManager.GetString("RCRReteFte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Retención de Industria y Comercio.
        '''</summary>
        Friend ReadOnly Property RCRRetIca() As String
            Get
                Return ResourceManager.GetString("RCRRetIca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversión Retención del IVA.
        '''</summary>
        Friend ReadOnly Property RCRRetIva() As String
            Get
                Return ResourceManager.GetString("RCRRetIva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El Año actual no ha sido Creado. Es necesario hacerlo antes de seguir adelante!.
        '''</summary>
        Friend ReadOnly Property VerAnoActual() As String
            Get
                Return ResourceManager.GetString("VerAnoActual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de seguir adelante, se debe crear y parametrizar el Año Inicial!.
        '''</summary>
        Friend ReadOnly Property VerAnos() As String
            Get
                Return ResourceManager.GetString("VerAnos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de seguir adelante, es necesario establecer las Cuentas Bancarias!.
        '''</summary>
        Friend ReadOnly Property VerBancos() As String
            Get
                Return ResourceManager.GetString("VerBancos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de seguir adelante, es necesario definir las Opciones de la Copropiedad!.
        '''</summary>
        Friend ReadOnly Property VerCenUtil() As String
            Get
                Return ResourceManager.GetString("VerCenUtil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Es necesario crear o importar los Clientes de la Copropiedad antes de seguir adelante!.
        '''</summary>
        Friend ReadOnly Property VerClientes() As String
            Get
                Return ResourceManager.GetString("VerClientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de seguir adelante, es necesario calcular los Coeficientes de Propiedad!.
        '''</summary>
        Friend ReadOnly Property VerCoefProp() As String
            Get
                Return ResourceManager.GetString("VerCoefProp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de seguir adelante, se deben crear las Cuentas de Contabilidad necesarias para la Interfaz Contable!.
        '''</summary>
        Friend ReadOnly Property VerCtasCont() As String
            Get
                Return ResourceManager.GetString("VerCtasCont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Es necesario verificar los Documentos Contables!.
        '''</summary>
        Friend ReadOnly Property VerDocs() As String
            Get
                Return ResourceManager.GetString("VerDocs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Es necesario definir los Documentos Contables!.
        '''</summary>
        Friend ReadOnly Property VerDocsNoDef() As String
            Get
                Return ResourceManager.GetString("VerDocsNoDef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de seguir adelante, es necesario crear los Modulos de la Copropiedad!.
        '''</summary>
        Friend ReadOnly Property VerModulos() As String
            Get
                Return ResourceManager.GetString("VerModulos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de seguir adelante, es necesario importar o crear los Predios de la Copropiedad!.
        '''</summary>
        Friend ReadOnly Property VerPredios() As String
            Get
                Return ResourceManager.GetString("VerPredios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de seguir adelante, es necesario crear o importar los Propietarios!.
        '''</summary>
        Friend ReadOnly Property VerProp() As String
            Get
                Return ResourceManager.GetString("VerProp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de seguir adelante, es necesario crear los Sectores de la Copropiedad!.
        '''</summary>
        Friend ReadOnly Property VerSect() As String
            Get
                Return ResourceManager.GetString("VerSect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Para seguir adelante, es necesario asignar los Sectores que contribuyen a cada uno de los Modulos!.
        '''</summary>
        Friend ReadOnly Property VerSectModulo() As String
            Get
                Return ResourceManager.GetString("VerSectModulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Para continuar, se deben crear los Servicios del Año.
        '''</summary>
        Friend ReadOnly Property VerServicioAno() As String
            Get
                Return ResourceManager.GetString("VerServicioAno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Para continuar, se debe crear al menos un servicio permanente!.
        '''</summary>
        Friend ReadOnly Property VerServiciosPer() As String
            Get
                Return ResourceManager.GetString("VerServiciosPer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de seguir adelante, es necesario establecer las Tasas de Mora para el cobro de Intereses!.
        '''</summary>
        Friend ReadOnly Property VerTasasMora() As String
            Get
                Return ResourceManager.GetString("VerTasasMora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de seguir adelante, es necesario crear o importar los Terceros!.
        '''</summary>
        Friend ReadOnly Property VerTerceros() As String
            Get
                Return ResourceManager.GetString("VerTerceros", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
