'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OPT.OrionP.OriIntCon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AdditionalAccountID&quot;: .
        '''</summary>
        Friend ReadOnly Property AddAcc() As String
            Get
                Return ResourceManager.GetString("AddAcc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AdditionalCustomer&quot;: .
        '''</summary>
        Friend ReadOnly Property AddCus() As String
            Get
                Return ResourceManager.GetString("AddCus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AdditionalDocument&quot;: [.
        '''</summary>
        Friend ReadOnly Property AddDoc() As String
            Get
                Return ResourceManager.GetString("AddDoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AdditionalDocuments&quot;: {.
        '''</summary>
        Friend ReadOnly Property AddDocs() As String
            Get
                Return ResourceManager.GetString("AddDocs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AddressLine&quot;: .
        '''</summary>
        Friend ReadOnly Property AddLin() As String
            Get
                Return ResourceManager.GetString("AddLin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AdditionalProperty&quot;: [.
        '''</summary>
        Friend ReadOnly Property AddPro() As String
            Get
                Return ResourceManager.GetString("AddPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AdditionalProperty&quot;: [.
        '''</summary>
        Friend ReadOnly Property AddProFac() As String
            Get
                Return ResourceManager.GetString("AddProFac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AdditionalReference&quot;: [.
        '''</summary>
        Friend ReadOnly Property AddRef() As String
            Get
                Return ResourceManager.GetString("AddRef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Attach&quot;: [.
        '''</summary>
        Friend ReadOnly Property Adjunto() As String
            Get
                Return ResourceManager.GetString("Adjunto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AllowanceCharge&quot;: [.
        '''</summary>
        Friend ReadOnly Property AllChar() As String
            Get
                Return ResourceManager.GetString("AllChar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AllowanceChargeReason&quot;: .
        '''</summary>
        Friend ReadOnly Property AllCharReas() As String
            Get
                Return ResourceManager.GetString("AllCharReas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AllowanceTotalAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property AllTotAmo() As String
            Get
                Return ResourceManager.GetString("AllTotAmo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Amount&quot;: .
        '''</summary>
        Friend ReadOnly Property Amount() As String
            Get
                Return ResourceManager.GetString("Amount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AdvancePayment&quot;: .
        '''</summary>
        Friend ReadOnly Property Anticip() As String
            Get
                Return ResourceManager.GetString("Anticip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PersonFamilyName&quot;: .
        '''</summary>
        Friend ReadOnly Property Apell1() As String
            Get
                Return ResourceManager.GetString("Apell1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PersonFamilyName2&quot;: .
        '''</summary>
        Friend ReadOnly Property Apell2() As String
            Get
                Return ResourceManager.GetString("Apell2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;BaseAmount&quot;:.
        '''</summary>
        Friend ReadOnly Property BasAmo() As String
            Get
                Return ResourceManager.GetString("BasAmo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TaxableAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property BaseImpto() As String
            Get
                Return ResourceManager.GetString("BaseImpto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;BaseUnitMeasure&quot;: .
        '''</summary>
        Friend ReadOnly Property BasUniMeas() As String
            Get
                Return ResourceManager.GetString("BasUniMeas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Additional_Fields&quot;:.
        '''</summary>
        Friend ReadOnly Property CampAdi() As String
            Get
                Return ResourceManager.GetString("CampAdi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AdditionalFields&quot;: .
        '''</summary>
        Friend ReadOnly Property CamposAdic() As String
            Get
                Return ResourceManager.GetString("CamposAdic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AttachmentQuantity&quot;: .
        '''</summary>
        Friend ReadOnly Property CanAdo() As String
            Get
                Return ResourceManager.GetString("CanAdo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Quatity&quot;: .
        '''</summary>
        Friend ReadOnly Property Cant() As String
            Get
                Return ResourceManager.GetString("Cant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ChargeIndicator&quot;: .
        '''</summary>
        Friend ReadOnly Property CharInd() As String
            Get
                Return ResourceManager.GetString("CharInd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ChargeTotalAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property ChaTotAmo() As String
            Get
                Return ResourceManager.GetString("ChaTotAmo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;CityCode&quot;: .
        '''</summary>
        Friend ReadOnly Property CitCod() As String
            Get
                Return ResourceManager.GetString("CitCod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;CityName&quot;: .
        '''</summary>
        Friend ReadOnly Property CitNam() As String
            Get
                Return ResourceManager.GetString("CitNam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;CityID&quot;: .
        '''</summary>
        Friend ReadOnly Property CiuDir() As String
            Get
                Return ResourceManager.GetString("CiuDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ResponseCode&quot;: .
        '''</summary>
        Friend ReadOnly Property CodConNota() As String
            Get
                Return ResourceManager.GetString("CodConNota", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ItemCode&quot;: .
        '''</summary>
        Friend ReadOnly Property CodItem() As String
            Get
                Return ResourceManager.GetString("CodItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Currency&quot;: .
        '''</summary>
        Friend ReadOnly Property CodMoneda() As String
            Get
                Return ResourceManager.GetString("CodMoneda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Note_Concept&quot;: {.
        '''</summary>
        Friend ReadOnly Property ConNota() As String
            Get
                Return ResourceManager.GetString("ConNota", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ContactPerson&quot;: .
        '''</summary>
        Friend ReadOnly Property ConPer() As String
            Get
                Return ResourceManager.GetString("ConPer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;CountryName&quot;: .
        '''</summary>
        Friend ReadOnly Property CouNam() As String
            Get
                Return ResourceManager.GetString("CouNam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;CUFE&quot;: .
        '''</summary>
        Friend ReadOnly Property Cufe() As String
            Get
                Return ResourceManager.GetString("Cufe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;CurrencyCode&quot;: .
        '''</summary>
        Friend ReadOnly Property CurCod() As String
            Get
                Return ResourceManager.GetString("CurCod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;CustomerCode&quot;: .
        '''</summary>
        Friend ReadOnly Property CusCod() As String
            Get
                Return ResourceManager.GetString("CusCod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Customer_Information&quot;: {.
        '''</summary>
        Friend ReadOnly Property CustInf() As String
            Get
                Return ResourceManager.GetString("CustInf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;CustomizationID&quot;: .
        '''</summary>
        Friend ReadOnly Property CustomId() As String
            Get
                Return ResourceManager.GetString("CustomId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;CustomizationIDInvoice&quot;: .
        '''</summary>
        Friend ReadOnly Property CustomIdInv() As String
            Get
                Return ResourceManager.GetString("CustomIdInv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;DeliveryCompany&quot;: .
        '''</summary>
        Friend ReadOnly Property DelCom() As String
            Get
                Return ResourceManager.GetString("DelCom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;DeliveryDate&quot;: .
        '''</summary>
        Friend ReadOnly Property DelDate() As String
            Get
                Return ResourceManager.GetString("DelDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Description&quot;: .
        '''</summary>
        Friend ReadOnly Property Descrip() As String
            Get
                Return ResourceManager.GetString("Descrip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;DespatchDocumentReference&quot;: .
        '''</summary>
        Friend ReadOnly Property DesDocRef() As String
            Get
                Return ResourceManager.GetString("DesDocRef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;DaysOff&quot;: .
        '''</summary>
        Friend ReadOnly Property DiasVen() As String
            Get
                Return ResourceManager.GetString("DiasVen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AddressLine&quot;: .
        '''</summary>
        Friend ReadOnly Property Dir() As String
            Get
                Return ResourceManager.GetString("Dir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;DiscrepancyCode&quot;: .
        '''</summary>
        Friend ReadOnly Property DisCod() As String
            Get
                Return ResourceManager.GetString("DisCod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;DocumentCode&quot;: .
        '''</summary>
        Friend ReadOnly Property DocCod() As String
            Get
                Return ResourceManager.GetString("DocCod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;DocumentNumber&quot;: .
        '''</summary>
        Friend ReadOnly Property DocNum() As String
            Get
                Return ResourceManager.GetString("DocNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;RegionID&quot;: .
        '''</summary>
        Friend ReadOnly Property DptoDir() As String
            Get
                Return ResourceManager.GetString("DptoDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Discount&quot;: .
        '''</summary>
        Friend ReadOnly Property Dscto() As String
            Get
                Return ResourceManager.GetString("Dscto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;DV&quot;: .
        '''</summary>
        Friend ReadOnly Property DV() As String
            Get
                Return ResourceManager.GetString("DV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Email&quot;: .
        '''</summary>
        Friend ReadOnly Property Email() As String
            Get
                Return ResourceManager.GetString("Email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Delivery&quot;: {.
        '''</summary>
        Friend ReadOnly Property Entrega() As String
            Get
                Return ResourceManager.GetString("Entrega", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;IsContingency&quot;: .
        '''</summary>
        Friend ReadOnly Property EsContin() As String
            Get
                Return ResourceManager.GetString("EsContin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;IsExport&quot;: .
        '''</summary>
        Friend ReadOnly Property EsExport() As String
            Get
                Return ResourceManager.GetString("EsExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TaxEvidenceIndicator&quot;: .
        '''</summary>
        Friend ReadOnly Property EsImpto() As String
            Get
                Return ResourceManager.GetString("EsImpto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ExchangeRate&quot;: .
        '''</summary>
        Friend ReadOnly Property ExchRate() As String
            Get
                Return ResourceManager.GetString("ExchRate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ExchangeRateDate&quot;: .
        '''</summary>
        Friend ReadOnly Property ExchRateDate() As String
            Get
                Return ResourceManager.GetString("ExchRateDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ExternalGR&quot;:  .
        '''</summary>
        Friend ReadOnly Property ExtGR() As String
            Get
                Return ResourceManager.GetString("ExtGR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ReceiptDocumentIssueDate&quot;: .
        '''</summary>
        Friend ReadOnly Property FeccAvisRecibo() As String
            Get
                Return ResourceManager.GetString("FeccAvisRecibo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;OrderReferenceIssueDate&quot;: .
        '''</summary>
        Friend ReadOnly Property FecOrdCompra() As String
            Get
                Return ResourceManager.GetString("FecOrdCompra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;DespatchDocumentIssueDate&quot;: .
        '''</summary>
        Friend ReadOnly Property FecOrdDespacho() As String
            Get
                Return ResourceManager.GetString("FecOrdDespacho", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;InvoiceDueDate&quot;: .
        '''</summary>
        Friend ReadOnly Property FecVen() As String
            Get
                Return ResourceManager.GetString("FecVen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;FiscalResponsabilities&quot;: .
        '''</summary>
        Friend ReadOnly Property FisRes() As String
            Get
                Return ResourceManager.GetString("FisRes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;FreeOFChargeIndicator&quot;: .
        '''</summary>
        Friend ReadOnly Property FreOfChargeInd() As String
            Get
                Return ResourceManager.GetString("FreOfChargeInd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Id&quot;: .
        '''</summary>
        Friend ReadOnly Property Id() As String
            Get
                Return ResourceManager.GetString("Id", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;DocumentId&quot;: .
        '''</summary>
        Friend ReadOnly Property IdDoc() As String
            Get
                Return ResourceManager.GetString("IdDoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Identification&quot;: .
        '''</summary>
        Friend ReadOnly Property Ident() As String
            Get
                Return ResourceManager.GetString("Ident", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PartyTaxLevelCode&quot;: .
        '''</summary>
        Friend ReadOnly Property IdReg() As String
            Get
                Return ResourceManager.GetString("IdReg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;IdentificationType&quot;: .
        '''</summary>
        Friend ReadOnly Property IdTipo() As String
            Get
                Return ResourceManager.GetString("IdTipo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;CustomerInformation&quot;: {.
        '''</summary>
        Friend ReadOnly Property InfCli() As String
            Get
                Return ResourceManager.GetString("InfCli", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Invoice_Information&quot;: [.
        '''</summary>
        Friend ReadOnly Property InfFac() As String
            Get
                Return ResourceManager.GetString("InfFac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Taxes_Information&quot;: [.
        '''</summary>
        Friend ReadOnly Property InfImptos() As String
            Get
                Return ResourceManager.GetString("InfImptos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TaxesInformation&quot;: [.
        '''</summary>
        Friend ReadOnly Property InfImptosFac() As String
            Get
                Return ResourceManager.GetString("InfImptosFac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ItemInformation&quot;: [.
        '''</summary>
        Friend ReadOnly Property InfItems() As String
            Get
                Return ResourceManager.GetString("InfItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Note_Information&quot;: {.
        '''</summary>
        Friend ReadOnly Property InfNota() As String
            Get
                Return ResourceManager.GetString("InfNota", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Interest&quot;: .
        '''</summary>
        Friend ReadOnly Property Interes() As String
            Get
                Return ResourceManager.GetString("Interes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;InvoiceAllowanceCharge&quot;: [.
        '''</summary>
        Friend ReadOnly Property InvAllChar() As String
            Get
                Return ResourceManager.GetString("InvAllChar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;InvoiceGeneralInformation&quot;: {.
        '''</summary>
        Friend ReadOnly Property InvGralInf() As String
            Get
                Return ResourceManager.GetString("InvGralInf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;InvoiceTaxTotal&quot;: [.
        '''</summary>
        Friend ReadOnly Property InvTaxTot() As String
            Get
                Return ResourceManager.GetString("InvTaxTot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;InvoiceTotal&quot;: {.
        '''</summary>
        Friend ReadOnly Property InvTotal() As String
            Get
                Return ResourceManager.GetString("InvTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;IssueDate&quot;: .
        '''</summary>
        Friend ReadOnly Property IssDate() As String
            Get
                Return ResourceManager.GetString("IssDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;IssueDateInvoice&quot;:.
        '''</summary>
        Friend ReadOnly Property IssDateInv() As String
            Get
                Return ResourceManager.GetString("IssDateInv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;IssueDateNote&quot;: .
        '''</summary>
        Friend ReadOnly Property IssDateNot() As String
            Get
                Return ResourceManager.GetString("IssDateNot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Item_Information&quot;: [.
        '''</summary>
        Friend ReadOnly Property ItemInf() As String
            Get
                Return ResourceManager.GetString("ItemInf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ItemReference&quot;: .
        '''</summary>
        Friend ReadOnly Property ItemRef() As String
            Get
                Return ResourceManager.GetString("ItemRef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;LineAllowanceTotal&quot;: .
        '''</summary>
        Friend ReadOnly Property LinAllTotal() As String
            Get
                Return ResourceManager.GetString("LinAllTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;LineChargeTotal&quot;: .
        '''</summary>
        Friend ReadOnly Property LinChrTotal() As String
            Get
                Return ResourceManager.GetString("LinChrTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;LineExtensionAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property LineExtCant() As String
            Get
                Return ResourceManager.GetString("LineExtCant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;LineExtensionAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property LinExtAmo() As String
            Get
                Return ResourceManager.GetString("LinExtAmo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;LineTotal&quot;: .
        '''</summary>
        Friend ReadOnly Property LinTot() As String
            Get
                Return ResourceManager.GetString("LinTot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;LineTotalTaxes&quot;: .
        '''</summary>
        Friend ReadOnly Property LinTotTax() As String
            Get
                Return ResourceManager.GetString("LinTotTax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;MeasureUnitCode&quot;: .
        '''</summary>
        Friend ReadOnly Property MesUniCod() As String
            Get
                Return ResourceManager.GetString("MesUniCod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;MultiplierFactorNumeric&quot;: .
        '''</summary>
        Friend ReadOnly Property MulFacNum() As String
            Get
                Return ResourceManager.GetString("MulFacNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Name&quot;: .
        '''</summary>
        Friend ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PersonFirstName&quot;: .
        '''</summary>
        Friend ReadOnly Property Nom1() As String
            Get
                Return ResourceManager.GetString("Nom1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PersonMiddleName&quot;: .
        '''</summary>
        Friend ReadOnly Property Nom2() As String
            Get
                Return ResourceManager.GetString("Nom2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;FileName&quot;: .
        '''</summary>
        Friend ReadOnly Property NomArchivo() As String
            Get
                Return ResourceManager.GetString("NomArchivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Name&quot;: .
        '''</summary>
        Friend ReadOnly Property Nombre() As String
            Get
                Return ResourceManager.GetString("Nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Note&quot;: .
        '''</summary>
        Friend ReadOnly Property Nota() As String
            Get
                Return ResourceManager.GetString("Nota", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Invoice_Note&quot;: {.
        '''</summary>
        Friend ReadOnly Property NotaFacCab() As String
            Get
                Return ResourceManager.GetString("NotaFacCab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;NoteGeneralInformation&quot;:{.
        '''</summary>
        Friend ReadOnly Property NotGralInf() As String
            Get
                Return ResourceManager.GetString("NotGralInf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;NoteNumber&quot;: .
        '''</summary>
        Friend ReadOnly Property NotNum() As String
            Get
                Return ResourceManager.GetString("NotNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;NoteTaxTotal&quot;: [.
        '''</summary>
        Friend ReadOnly Property NotTaxTot() As String
            Get
                Return ResourceManager.GetString("NotTaxTot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;NoteTotal&quot;: {.
        '''</summary>
        Friend ReadOnly Property NotTot() As String
            Get
                Return ResourceManager.GetString("NotTot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;InvoiceNumber&quot;: .
        '''</summary>
        Friend ReadOnly Property NroFac() As String
            Get
                Return ResourceManager.GetString("NroFac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PreinvoiceNumber&quot;: .
        '''</summary>
        Friend ReadOnly Property NroPreFac() As String
            Get
                Return ResourceManager.GetString("NroPreFac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;InvoiceAuthorizationNumber&quot;: .
        '''</summary>
        Friend ReadOnly Property NroResAut() As String
            Get
                Return ResourceManager.GetString("NroResAut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;OrderReference&quot;: .
        '''</summary>
        Friend ReadOnly Property OrdRef() As String
            Get
                Return ResourceManager.GetString("OrdRef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;WebSiteURI&quot;: .
        '''</summary>
        Friend ReadOnly Property PagInt() As String
            Get
                Return ResourceManager.GetString("PagInt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;CountryCode&quot;: .
        '''</summary>
        Friend ReadOnly Property PaisDir() As String
            Get
                Return ResourceManager.GetString("PaisDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PartecipationPercent&quot;: .
        '''</summary>
        Friend ReadOnly Property PartPer() As String
            Get
                Return ResourceManager.GetString("PartPer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PayableAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property PayAmo() As String
            Get
                Return ResourceManager.GetString("PayAmo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PaymentMeans&quot;: .
        '''</summary>
        Friend ReadOnly Property PayMeans() As String
            Get
                Return ResourceManager.GetString("PayMeans", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Payment_Summary&quot;: {.
        '''</summary>
        Friend ReadOnly Property PaymSum() As String
            Get
                Return ResourceManager.GetString("PaymSum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PaymentNote&quot;: .
        '''</summary>
        Friend ReadOnly Property PayNot() As String
            Get
                Return ResourceManager.GetString("PayNot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PaymentType&quot;: .
        '''</summary>
        Friend ReadOnly Property PayTyp() As String
            Get
                Return ResourceManager.GetString("PayTyp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;EndAffectedPeriod&quot;:.
        '''</summary>
        Friend ReadOnly Property PeriodoEnd() As String
            Get
                Return ResourceManager.GetString("PeriodoEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;StartAffectedPeriod&quot;:.
        '''</summary>
        Friend ReadOnly Property PeriodoStart() As String
            Get
                Return ResourceManager.GetString("PeriodoStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PerUnitAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property PerUniAmo() As String
            Get
                Return ResourceManager.GetString("PerUniAmo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PostalZone&quot;: .
        '''</summary>
        Friend ReadOnly Property PosZon() As String
            Get
                Return ResourceManager.GetString("PosZon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Price&quot;: .
        '''</summary>
        Friend ReadOnly Property Precio() As String
            Get
                Return ResourceManager.GetString("Precio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Prefix&quot;: .
        '''</summary>
        Friend ReadOnly Property Pref() As String
            Get
                Return ResourceManager.GetString("Pref", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PrePaidAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property PrePaiAmo() As String
            Get
                Return ResourceManager.GetString("PrePaiAmo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;AdditionalItemPropertyList&quot;: .
        '''</summary>
        Friend ReadOnly Property PropAdiItemFac() As String
            Get
                Return ResourceManager.GetString("PropAdiItemFac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Quantity&quot;: .
        '''</summary>
        Friend ReadOnly Property Quan() As String
            Get
                Return ResourceManager.GetString("Quan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;RegistrationName&quot;: .
        '''</summary>
        Friend ReadOnly Property RazonS() As String
            Get
                Return ResourceManager.GetString("RazonS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ReceiptDocumentReference&quot;: .
        '''</summary>
        Friend ReadOnly Property RecDocRef() As String
            Get
                Return ResourceManager.GetString("RecDocRef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ReferenceCode&quot;: .
        '''</summary>
        Friend ReadOnly Property RefCod() As String
            Get
                Return ResourceManager.GetString("RefCod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ReferenceID&quot;: .
        '''</summary>
        Friend ReadOnly Property RefId() As String
            Get
                Return ResourceManager.GetString("RefId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;ReferenceNumber&quot;: .
        '''</summary>
        Friend ReadOnly Property RefNum() As String
            Get
                Return ResourceManager.GetString("RefNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PartyTaxLevelCode&quot;: .
        '''</summary>
        Friend ReadOnly Property RegimenTri() As String
            Get
                Return ResourceManager.GetString("RegimenTri", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;RegistrationName&quot;: .
        '''</summary>
        Friend ReadOnly Property Regist() As String
            Get
                Return ResourceManager.GetString("Regist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PaymentSummary&quot;: {.
        '''</summary>
        Friend ReadOnly Property ResuPago() As String
            Get
                Return ResourceManager.GetString("ResuPago", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;SalesPerson&quot;: .
        '''</summary>
        Friend ReadOnly Property SalPer() As String
            Get
                Return ResourceManager.GetString("SalPer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;SubdivisionCode&quot;: .
        '''</summary>
        Friend ReadOnly Property SubCod() As String
            Get
                Return ResourceManager.GetString("SubCod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;SubdivisionName&quot;: .
        '''</summary>
        Friend ReadOnly Property SubNam() As String
            Get
                Return ResourceManager.GetString("SubNam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Percent&quot;: .
        '''</summary>
        Friend ReadOnly Property Tasa() As String
            Get
                Return ResourceManager.GetString("Tasa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TaxExclusiveAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property TaxExcAmo() As String
            Get
                Return ResourceManager.GetString("TaxExcAmo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TaxExclusiveAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property TaxExclCant() As String
            Get
                Return ResourceManager.GetString("TaxExclCant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TaxInclusiveAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property TaxIncAmo() As String
            Get
                Return ResourceManager.GetString("TaxIncAmo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TaxesInformation&quot;: [.
        '''</summary>
        Friend ReadOnly Property TaxInf() As String
            Get
                Return ResourceManager.GetString("TaxInf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TaxLevelCodeListName&quot;: .
        '''</summary>
        Friend ReadOnly Property TaxLev() As String
            Get
                Return ResourceManager.GetString("TaxLev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TaxSchemeCode&quot;: .
        '''</summary>
        Friend ReadOnly Property TaxSchCod() As String
            Get
                Return ResourceManager.GetString("TaxSchCod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TaxSchemeName&quot;: .
        '''</summary>
        Friend ReadOnly Property TaxSchName() As String
            Get
                Return ResourceManager.GetString("TaxSchName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Telephone&quot;: .
        '''</summary>
        Friend ReadOnly Property Tel() As String
            Get
                Return ResourceManager.GetString("Tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Telephone&quot;: .
        '''</summary>
        Friend ReadOnly Property Teleph() As String
            Get
                Return ResourceManager.GetString("Teleph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TypeFile&quot;: .
        '''</summary>
        Friend ReadOnly Property TipoArchivo() As String
            Get
                Return ResourceManager.GetString("TipoArchivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;DocumentType&quot;: .
        '''</summary>
        Friend ReadOnly Property TipoDoc() As String
            Get
                Return ResourceManager.GetString("TipoDoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;IdentificationType&quot;: .
        '''</summary>
        Friend ReadOnly Property TipoId() As String
            Get
                Return ResourceManager.GetString("TipoId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;PersonTypeID&quot;: .
        '''</summary>
        Friend ReadOnly Property TipoPers() As String
            Get
                Return ResourceManager.GetString("TipoPers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Value&quot;: .
        '''</summary>
        Friend ReadOnly Property Valor() As String
            Get
                Return ResourceManager.GetString("Valor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;Amount&quot;: .
        '''</summary>
        Friend ReadOnly Property ValorItem() As String
            Get
                Return ResourceManager.GetString("ValorItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &quot;TaxAmount&quot;: .
        '''</summary>
        Friend ReadOnly Property VlrImpto() As String
            Get
                Return ResourceManager.GetString("VlrImpto", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
