'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OPT.OrionP.RepOriCop.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a _Cancelar.
        '''</summary>
        Friend ReadOnly Property Cancelar() As String
            Get
                Return ResourceManager.GetString("Cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;Ninguno&gt;.
        '''</summary>
        Friend ReadOnly Property Ninguno() As String
            Get
                Return ResourceManager.GetString("Ninguno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aplicado a Capital.
        '''</summary>
        Friend ReadOnly Property RCAbonoCap() As String
            Get
                Return ResourceManager.GetString("RCAbonoCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aplicado a Int. de Mora.
        '''</summary>
        Friend ReadOnly Property RCAbonoMor() As String
            Get
                Return ResourceManager.GetString("RCAbonoMor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Anticipo recibido.
        '''</summary>
        Friend ReadOnly Property RCAnticipo() As String
            Get
                Return ResourceManager.GetString("RCAnticipo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descuento a Capital.
        '''</summary>
        Friend ReadOnly Property RCDsctoCap() As String
            Get
                Return ResourceManager.GetString("RCDsctoCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descuento a Int. de Mora.
        '''</summary>
        Friend ReadOnly Property RCDsctoMor() As String
            Get
                Return ResourceManager.GetString("RCDsctoMor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descuento por Pronto Pago.
        '''</summary>
        Friend ReadOnly Property RCDsctoPP() As String
            Get
                Return ResourceManager.GetString("RCDsctoPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención del CREE.
        '''</summary>
        Friend ReadOnly Property RCRetCre() As String
            Get
                Return ResourceManager.GetString("RCRetCre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención en la Fuente.
        '''</summary>
        Friend ReadOnly Property RCReteFte() As String
            Get
                Return ResourceManager.GetString("RCReteFte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención de Industria y Comercio.
        '''</summary>
        Friend ReadOnly Property RCRetIca() As String
            Get
                Return ResourceManager.GetString("RCRetIca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Retención del IVA.
        '''</summary>
        Friend ReadOnly Property RCRetIva() As String
            Get
                Return ResourceManager.GetString("RCRetIva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Auxiliar Contable.
        '''</summary>
        Friend ReadOnly Property RepAuxiliarCon() As String
            Get
                Return ResourceManager.GetString("RepAuxiliarCon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sin Pred. Agr..
        '''</summary>
        Friend ReadOnly Property SinPredAgr() As String
            Get
                Return ResourceManager.GetString("SinPredAgr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reporte: .
        '''</summary>
        Friend ReadOnly Property TituloRep() As String
            Get
                Return ResourceManager.GetString("TituloRep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;Todos&gt;.
        '''</summary>
        Friend ReadOnly Property Todos() As String
            Get
                Return ResourceManager.GetString("Todos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vista Previa Impresión Auxiliar.
        '''</summary>
        Friend ReadOnly Property VPImpresionAux() As String
            Get
                Return ResourceManager.GetString("VPImpresionAux", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vista Previa Impresión Auxiliar Terceros.
        '''</summary>
        Friend ReadOnly Property VPImpresionAuxTer() As String
            Get
                Return ResourceManager.GetString("VPImpresionAuxTer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vista Previa Impresión Facturas.
        '''</summary>
        Friend ReadOnly Property VPImpresionFacturas() As String
            Get
                Return ResourceManager.GetString("VPImpresionFacturas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vista Previa Impresión Notas Aplicación Anticipos.
        '''</summary>
        Friend ReadOnly Property VPImpresionNotasAplAnt() As String
            Get
                Return ResourceManager.GetString("VPImpresionNotasAplAnt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vista Previa Impresión Nota Crédito.
        '''</summary>
        Friend ReadOnly Property VPImpresionNotasCr() As String
            Get
                Return ResourceManager.GetString("VPImpresionNotasCr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vista Previa Impresión Nota Reintegro Anticipos.
        '''</summary>
        Friend ReadOnly Property VPImpresionNotasDevAnt() As String
            Get
                Return ResourceManager.GetString("VPImpresionNotasDevAnt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vista Previa Impresión Notas de Intereses.
        '''</summary>
        Friend ReadOnly Property VPImpresionNotasIntereses() As String
            Get
                Return ResourceManager.GetString("VPImpresionNotasIntereses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vista Previa Impresión Recibos de Caja.
        '''</summary>
        Friend ReadOnly Property VPImpresionRecibos() As String
            Get
                Return ResourceManager.GetString("VPImpresionRecibos", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
