'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OPT.OrionP.OrionCopIU.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre la Ayuda de Panorama..
        '''</summary>
        Friend ReadOnly Property AbreAyuda() As String
            Get
                Return ResourceManager.GetString("AbreAyuda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAyuda.
        '''</summary>
        Friend ReadOnly Property AbreAyudaCmd() As String
            Get
                Return ResourceManager.GetString("AbreAyudaCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre el Bloc de Notas de Windows..
        '''</summary>
        Friend ReadOnly Property AbreBloc() As String
            Get
                Return ResourceManager.GetString("AbreBloc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdNotas.
        '''</summary>
        Friend ReadOnly Property AbreBlocCmd() As String
            Get
                Return ResourceManager.GetString("AbreBlocCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre la Calculadora de Windows..
        '''</summary>
        Friend ReadOnly Property AbreCalc() As String
            Get
                Return ResourceManager.GetString("AbreCalc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdCalculadora.
        '''</summary>
        Friend ReadOnly Property AbreCalcCmd() As String
            Get
                Return ResourceManager.GetString("AbreCalcCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre el Calendario de Windows..
        '''</summary>
        Friend ReadOnly Property AbreCalendario() As String
            Get
                Return ResourceManager.GetString("AbreCalendario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdCalendario.
        '''</summary>
        Friend ReadOnly Property AbreCalendarioCmd() As String
            Get
                Return ResourceManager.GetString("AbreCalendarioCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre los Mensajes de Panorama..
        '''</summary>
        Friend ReadOnly Property AbreMens() As String
            Get
                Return ResourceManager.GetString("AbreMens", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdMensajes.
        '''</summary>
        Friend ReadOnly Property AbreMensCmd() As String
            Get
                Return ResourceManager.GetString("AbreMensCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Acepta los cambios en la Ventana..
        '''</summary>
        Friend ReadOnly Property AceptaCam() As String
            Get
                Return ResourceManager.GetString("AceptaCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAceptar.
        '''</summary>
        Friend ReadOnly Property AceptaCamCmd() As String
            Get
                Return ResourceManager.GetString("AceptaCamCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administración.
        '''</summary>
        Friend ReadOnly Property Admin() As String
            Get
                Return ResourceManager.GetString("Admin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ADVERTENCIA: .
        '''</summary>
        Friend ReadOnly Property Advertencia() As String
            Get
                Return ResourceManager.GetString("Advertencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ajuste Cuota.
        '''</summary>
        Friend ReadOnly Property AjuCuota() As String
            Get
                Return ResourceManager.GetString("AjuCuota", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ajustando Cuotas de Administración.
        '''</summary>
        Friend ReadOnly Property AjusCuoAdm() As String
            Get
                Return ResourceManager.GetString("AjusCuoAdm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Año.
        '''</summary>
        Friend ReadOnly Property Ano() As String
            Get
                Return ResourceManager.GetString("Ano", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Años.
        '''</summary>
        Friend ReadOnly Property Anos() As String
            Get
                Return ResourceManager.GetString("Anos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generando Reporte Anticipos por Aplicar.
        '''</summary>
        Friend ReadOnly Property AntPorApl() As String
            Get
                Return ResourceManager.GetString("AntPorApl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Anticipo recibido.
        '''</summary>
        Friend ReadOnly Property AntRec() As String
            Get
                Return ResourceManager.GetString("AntRec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAnular.
        '''</summary>
        Friend ReadOnly Property AnuCmd() As String
            Get
                Return ResourceManager.GetString("AnuCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Anular un Objeto.
        '''</summary>
        Friend ReadOnly Property AnuObj() As String
            Get
                Return ResourceManager.GetString("AnuObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aplicando Anticipos.
        '''</summary>
        Friend ReadOnly Property AplAnticipos() As String
            Get
                Return ResourceManager.GetString("AplAnticipos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  - Aplicación.
        '''</summary>
        Friend ReadOnly Property App() As String
            Get
                Return ResourceManager.GetString("App", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aplicación Contable para Interfaz.
        '''</summary>
        Friend ReadOnly Property AppCont() As String
            Get
                Return ResourceManager.GetString("AppCont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Archivo externo.
        '''</summary>
        Friend ReadOnly Property ArchExt() As String
            Get
                Return ResourceManager.GetString("ArchExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Base para el Cálculo del Coediciente de Propiedad .
        '''</summary>
        Friend ReadOnly Property BaseCP() As String
            Get
                Return ResourceManager.GetString("BaseCP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Base del Redondeo para Coeficiente de Propiedad.
        '''</summary>
        Friend ReadOnly Property BaseRedCP() As String
            Get
                Return ResourceManager.GetString("BaseRedCP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Base del Redondeo para operaciones en general.
        '''</summary>
        Friend ReadOnly Property BaseRedGral() As String
            Get
                Return ResourceManager.GetString("BaseRedGral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Base del Redondeo para Intereses de Mora.
        '''</summary>
        Friend ReadOnly Property BaseRedIM() As String
            Get
                Return ResourceManager.GetString("BaseRedIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a C_errar.
        '''</summary>
        Friend ReadOnly Property BtnCerrar() As String
            Get
                Return ResourceManager.GetString("BtnCerrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generar _Reporte.
        '''</summary>
        Friend ReadOnly Property BtnGenRep() As String
            Get
                Return ResourceManager.GetString("BtnGenRep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Calendario.
        '''</summary>
        Friend ReadOnly Property Calendario() As String
            Get
                Return ResourceManager.GetString("Calendario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aún hay campos requeridos por satisfacer!.
        '''</summary>
        Friend ReadOnly Property CamposSinSatisfacer() As String
            Get
                Return ResourceManager.GetString("CamposSinSatisfacer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancela los cambios en la Ventana..
        '''</summary>
        Friend ReadOnly Property CancelaCam() As String
            Get
                Return ResourceManager.GetString("CancelaCam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdCancelar.
        '''</summary>
        Friend ReadOnly Property CancelaCamCmd() As String
            Get
                Return ResourceManager.GetString("CancelaCamCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a _Cancelar.
        '''</summary>
        Friend ReadOnly Property Cancelar() As String
            Get
                Return ResourceManager.GetString("Cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  - Empresa.
        '''</summary>
        Friend ReadOnly Property Carpeta() As String
            Get
                Return ResourceManager.GetString("Carpeta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  - Copropiedad.
        '''</summary>
        Friend ReadOnly Property CenUti() As String
            Get
                Return ResourceManager.GetString("CenUti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.
        '''</summary>
        Friend ReadOnly Property Cero() As String
            Get
                Return ResourceManager.GetString("Cero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a _Cerrar.
        '''</summary>
        Friend ReadOnly Property CerrarBtn() As String
            Get
                Return ResourceManager.GetString("CerrarBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cierra la Ventana actual..
        '''</summary>
        Friend ReadOnly Property CierraWin() As String
            Get
                Return ResourceManager.GetString("CierraWin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdCerrar.
        '''</summary>
        Friend ReadOnly Property CierraWinCmd() As String
            Get
                Return ResourceManager.GetString("CierraWinCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cliente.
        '''</summary>
        Friend ReadOnly Property Cliente() As String
            Get
                Return ResourceManager.GetString("Cliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cobro persuasivo.
        '''</summary>
        Friend ReadOnly Property CobPer() As String
            Get
                Return ResourceManager.GetString("CobPer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Coeficientes de Propiedad por Propietario.
        '''</summary>
        Friend ReadOnly Property CoefPropProp() As String
            Get
                Return ResourceManager.GetString("CoefPropProp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ,.
        '''</summary>
        Friend ReadOnly Property Coma() As String
            Get
                Return ResourceManager.GetString("Coma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Compara con Tasa de Usura.
        '''</summary>
        Friend ReadOnly Property ComparaTU() As String
            Get
                Return ResourceManager.GetString("ComparaTU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Copyright T&amp;&amp;S S.A.S..
        '''</summary>
        Friend ReadOnly Property CopyrightTYS() As String
            Get
                Return ResourceManager.GetString("CopyrightTYS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdCrear.
        '''</summary>
        Friend ReadOnly Property CrearCmd() As String
            Get
                Return ResourceManager.GetString("CrearCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Crear un Objeto.
        '''</summary>
        Friend ReadOnly Property CrearObj() As String
            Get
                Return ResourceManager.GetString("CrearObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuentas Bancarias.
        '''</summary>
        Friend ReadOnly Property CtaBanc() As String
            Get
                Return ResourceManager.GetString("CtaBanc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuentas Contables.
        '''</summary>
        Friend ReadOnly Property CtasConta() As String
            Get
                Return ResourceManager.GetString("CtasConta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta del Cliente.
        '''</summary>
        Friend ReadOnly Property CuentaCliente() As String
            Get
                Return ResourceManager.GetString("CuentaCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta del Predio.
        '''</summary>
        Friend ReadOnly Property CuentaPredio() As String
            Get
                Return ResourceManager.GetString("CuentaPredio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuotas de Administración.
        '''</summary>
        Friend ReadOnly Property CuotasAdmin() As String
            Get
                Return ResourceManager.GetString("CuotasAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  de .
        '''</summary>
        Friend ReadOnly Property De() As String
            Get
                Return ResourceManager.GetString("De", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Días para Cobro Jurídico.
        '''</summary>
        Friend ReadOnly Property DiasJuri() As String
            Get
                Return ResourceManager.GetString("DiasJuri", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dias para Pérdida.
        '''</summary>
        Friend ReadOnly Property DiasPerdida() As String
            Get
                Return ResourceManager.GetString("DiasPerdida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Días para Cobro Persuasivo.
        '''</summary>
        Friend ReadOnly Property DiasPersuasivo() As String
            Get
                Return ResourceManager.GetString("DiasPersuasivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Días para Cobro Prejurídico.
        '''</summary>
        Friend ReadOnly Property DiasPreju() As String
            Get
                Return ResourceManager.GetString("DiasPreju", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Documento.
        '''</summary>
        Friend ReadOnly Property Doc() As String
            Get
                Return ResourceManager.GetString("Doc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Documentos.
        '''</summary>
        Friend ReadOnly Property Docs() As String
            Get
                Return ResourceManager.GetString("Docs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DOCUMENTOS.
        '''</summary>
        Friend ReadOnly Property Documentos() As String
            Get
                Return ResourceManager.GetString("Documentos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a : .
        '''</summary>
        Friend ReadOnly Property DosPuntosEspacio() As String
            Get
                Return ResourceManager.GetString("DosPuntosEspacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Elementos Procesados : .
        '''</summary>
        Friend ReadOnly Property EleProce() As String
            Get
                Return ResourceManager.GetString("EleProce", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Eliminar firma.
        '''</summary>
        Friend ReadOnly Property ElimFirma() As String
            Get
                Return ResourceManager.GetString("ElimFirma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ERROR: .
        '''</summary>
        Friend ReadOnly Property ErrorStr() As String
            Get
                Return ResourceManager.GetString("ErrorStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ? Es Ajuste.
        '''</summary>
        Friend ReadOnly Property EsAjuste() As String
            Get
                Return ResourceManager.GetString("EsAjuste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Escriba aqui la descripción de la tarea..
        '''</summary>
        Friend ReadOnly Property EscribaTarea() As String
            Get
                Return ResourceManager.GetString("EscribaTarea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  .
        '''</summary>
        Friend ReadOnly Property Espacio() As String
            Get
                Return ResourceManager.GetString("Espacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Consultando.
        '''</summary>
        Friend ReadOnly Property EstConsultando() As String
            Get
                Return ResourceManager.GetString("EstConsultando", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Creando.
        '''</summary>
        Friend ReadOnly Property EstCreando() As String
            Get
                Return ResourceManager.GetString("EstCreando", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificando.
        '''</summary>
        Friend ReadOnly Property EstModificando() As String
            Get
                Return ResourceManager.GetString("EstModificando", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Exportando Facturas a PDF.
        '''</summary>
        Friend ReadOnly Property ExpFras() As String
            Get
                Return ResourceManager.GetString("ExpFras", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Rxportando Recibos de Caja.
        '''</summary>
        Friend ReadOnly Property ExpRec() As String
            Get
                Return ResourceManager.GetString("ExpRec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Una Factura.
        '''</summary>
        Friend ReadOnly Property Fact() As String
            Get
                Return ResourceManager.GetString("Fact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Facturas automáticas del Mes.
        '''</summary>
        Friend ReadOnly Property FactAuto() As String
            Get
                Return ResourceManager.GetString("FactAuto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Facturas procesadas: .
        '''</summary>
        Friend ReadOnly Property FactProcesadas() As String
            Get
                Return ResourceManager.GetString("FactProcesadas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha: .
        '''</summary>
        Friend ReadOnly Property Fecha() As String
            Get
                Return ResourceManager.GetString("Fecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha Anulación.
        '''</summary>
        Friend ReadOnly Property FechaAnulacion() As String
            Get
                Return ResourceManager.GetString("FechaAnulacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha Cancelación.
        '''</summary>
        Friend ReadOnly Property FechaCancelacion() As String
            Get
                Return ResourceManager.GetString("FechaCancelacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha Limite pago sin Mora.
        '''</summary>
        Friend ReadOnly Property FechaGracia() As String
            Get
                Return ResourceManager.GetString("FechaGracia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha de la Ultima Causación General.
        '''</summary>
        Friend ReadOnly Property FecUltCausa() As String
            Get
                Return ResourceManager.GetString("FecUltCausa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha Anticipos - Anticipo Número: .
        '''</summary>
        Friend ReadOnly Property FichaAnt() As String
            Get
                Return ResourceManager.GetString("FichaAnt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha Clientes - Cliente: .
        '''</summary>
        Friend ReadOnly Property FichaCliente() As String
            Get
                Return ResourceManager.GetString("FichaCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha Cuentas Cobro - Cuenta de Cobro Número: .
        '''</summary>
        Friend ReadOnly Property FichaCtaCobro() As String
            Get
                Return ResourceManager.GetString("FichaCtaCobro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha Notas Ajuste Cuota Administración - Nota Nro: .
        '''</summary>
        Friend ReadOnly Property FichaNAju() As String
            Get
                Return ResourceManager.GetString("FichaNAju", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha Notas Aplicación Anticipos - Nota Nro: .
        '''</summary>
        Friend ReadOnly Property FichaNApl() As String
            Get
                Return ResourceManager.GetString("FichaNApl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha Notas Crédito - Nota Nro: .
        '''</summary>
        Friend ReadOnly Property FichaNCr() As String
            Get
                Return ResourceManager.GetString("FichaNCr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha Notas Intereses Mora - Nota Nro: .
        '''</summary>
        Friend ReadOnly Property FichaNDb() As String
            Get
                Return ResourceManager.GetString("FichaNDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha Notas Reintegro de Anticipos - Nota Nro:.
        '''</summary>
        Friend ReadOnly Property FichaNDev() As String
            Get
                Return ResourceManager.GetString("FichaNDev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha Notas Reversión Créditos - Nota Nro: .
        '''</summary>
        Friend ReadOnly Property FichaNRevCr() As String
            Get
                Return ResourceManager.GetString("FichaNRevCr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha Predios - Predio: .
        '''</summary>
        Friend ReadOnly Property FichaPredio() As String
            Get
                Return ResourceManager.GetString("FichaPredio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha propietario.
        '''</summary>
        Friend ReadOnly Property FichaProp() As String
            Get
                Return ResourceManager.GetString("FichaProp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ficha Recibos de Caja - Recibo de Caja Número: .
        '''</summary>
        Friend ReadOnly Property FichaRec() As String
            Get
                Return ResourceManager.GetString("FichaRec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generando Copia de Seguridad.
        '''</summary>
        Friend ReadOnly Property GenBK() As String
            Get
                Return ResourceManager.GetString("GenBK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generando Reporte Edad de la Cartera.
        '''</summary>
        Friend ReadOnly Property GenEdadCar() As String
            Get
                Return ResourceManager.GetString("GenEdadCar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generando Estados de Cuenta Clientes.
        '''</summary>
        Friend ReadOnly Property GenEstadosCtasCli() As String
            Get
                Return ResourceManager.GetString("GenEstadosCtasCli", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generando Estados de Cuenta Predios.
        '''</summary>
        Friend ReadOnly Property GenEstadosCtasPre() As String
            Get
                Return ResourceManager.GetString("GenEstadosCtasPre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generando Facturas Definitivas.
        '''</summary>
        Friend ReadOnly Property GenFacturasDef() As String
            Get
                Return ResourceManager.GetString("GenFacturasDef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generando Intereses de Mora.
        '''</summary>
        Friend ReadOnly Property GenInte() As String
            Get
                Return ResourceManager.GetString("GenInte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a A CLIENTES.
        '''</summary>
        Friend ReadOnly Property GenPreClientes() As String
            Get
                Return ResourceManager.GetString("GenPreClientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a A PREDIOS.
        '''</summary>
        Friend ReadOnly Property GenPrePredios() As String
            Get
                Return ResourceManager.GetString("GenPrePredios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SOLO A PROPIETARIOS Y PREDIO AGRU..
        '''</summary>
        Friend ReadOnly Property GenPrePropPA() As String
            Get
                Return ResourceManager.GetString("GenPrePropPA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a A PROPIETARIOS SIN PREDIO AGRU..
        '''</summary>
        Friend ReadOnly Property GenPrePropSPA() As String
            Get
                Return ResourceManager.GetString("GenPrePropSPA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Grupo Carpetas.
        '''</summary>
        Friend ReadOnly Property GrpCarpetas() As String
            Get
                Return ResourceManager.GetString("GrpCarpetas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdGuardar.
        '''</summary>
        Friend ReadOnly Property GuaCmd() As String
            Get
                Return ResourceManager.GetString("GuaCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Guardar los cambios en el Objeto.
        '''</summary>
        Friend ReadOnly Property GuaObj() As String
            Get
                Return ResourceManager.GetString("GuaObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a - .
        '''</summary>
        Friend ReadOnly Property GuionSeparador() As String
            Get
                Return ResourceManager.GetString("GuionSeparador", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Id. Carpeta.
        '''</summary>
        Friend ReadOnly Property IdCarpeta() As String
            Get
                Return ResourceManager.GetString("IdCarpeta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Id. Copropiedad.
        '''</summary>
        Friend ReadOnly Property IdCenUtil() As String
            Get
                Return ResourceManager.GetString("IdCenUtil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Id. Cliente.
        '''</summary>
        Friend ReadOnly Property IdCliente() As String
            Get
                Return ResourceManager.GetString("IdCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta para Anticipos Recibidos.
        '''</summary>
        Friend ReadOnly Property IdCtaAntRec() As String
            Get
                Return ResourceManager.GetString("IdCtaAntRec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta para Caja.
        '''</summary>
        Friend ReadOnly Property IdCtaCaja() As String
            Get
                Return ResourceManager.GetString("IdCtaCaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta para Devoluciones de Capital.
        '''</summary>
        Friend ReadOnly Property IdCtaDctoCap() As String
            Get
                Return ResourceManager.GetString("IdCtaDctoCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta para Descuentos por Pronto Pago.
        '''</summary>
        Friend ReadOnly Property IdCtaDctoPP() As String
            Get
                Return ResourceManager.GetString("IdCtaDctoPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta para Impuetos Asumidos.
        '''</summary>
        Friend ReadOnly Property IdCtaImptosAsumidos() As String
            Get
                Return ResourceManager.GetString("IdCtaImptosAsumidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta para Ingresos por identificar.
        '''</summary>
        Friend ReadOnly Property IdCtaIngPorIden() As String
            Get
                Return ResourceManager.GetString("IdCtaIngPorIden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta para Intereses de Mora Crédito.
        '''</summary>
        Friend ReadOnly Property IdCtaInMoCr() As String
            Get
                Return ResourceManager.GetString("IdCtaInMoCr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta para Intereses de Mora Débito.
        '''</summary>
        Friend ReadOnly Property IdCtaInMoDb() As String
            Get
                Return ResourceManager.GetString("IdCtaInMoDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta para Retefuente.
        '''</summary>
        Friend ReadOnly Property IdCtaRetFte() As String
            Get
                Return ResourceManager.GetString("IdCtaRetFte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta para Retención de Industria y Comercio.
        '''</summary>
        Friend ReadOnly Property IdCtaRetIca() As String
            Get
                Return ResourceManager.GetString("IdCtaRetIca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta para ReteIva.
        '''</summary>
        Friend ReadOnly Property IdCtaRetIva() As String
            Get
                Return ResourceManager.GetString("IdCtaRetIva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Id. Predio.
        '''</summary>
        Friend ReadOnly Property IdPredio() As String
            Get
                Return ResourceManager.GetString("IdPredio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nro. del Recibo de Caja.
        '''</summary>
        Friend ReadOnly Property IdRecCaja() As String
            Get
                Return ResourceManager.GetString("IdRecCaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Id. Representante Legal.
        '''</summary>
        Friend ReadOnly Property IdRepLegal() As String
            Get
                Return ResourceManager.GetString("IdRepLegal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Id. Tercero Copropiedad.
        '''</summary>
        Friend ReadOnly Property IdTerCenUti() As String
            Get
                Return ResourceManager.GetString("IdTerCenUti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Importando Facturas de Saldos.
        '''</summary>
        Friend ReadOnly Property ImpFras() As String
            Get
                Return ResourceManager.GetString("ImpFras", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Importar firma.
        '''</summary>
        Friend ReadOnly Property ImporFirma() As String
            Get
                Return ResourceManager.GetString("ImporFirma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Importado.
        '''</summary>
        Friend ReadOnly Property Import() As String
            Get
                Return ResourceManager.GetString("Import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Importar.
        '''</summary>
        Friend ReadOnly Property Importar() As String
            Get
                Return ResourceManager.GetString("Importar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Importar Objeto.
        '''</summary>
        Friend ReadOnly Property ImportarObjeto() As String
            Get
                Return ResourceManager.GetString("ImportarObjeto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INFORMACION: .
        '''</summary>
        Friend ReadOnly Property Informacion() As String
            Get
                Return ResourceManager.GetString("Informacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAlAnterior.
        '''</summary>
        Friend ReadOnly Property IrAntCmd() As String
            Get
                Return ResourceManager.GetString("IrAntCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ir Al Anterior.
        '''</summary>
        Friend ReadOnly Property IrAntObj() As String
            Get
                Return ResourceManager.GetString("IrAntObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdBuscar.
        '''</summary>
        Friend ReadOnly Property IrBusCmd() As String
            Get
                Return ResourceManager.GetString("IrBusCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Busca un Objeto.
        '''</summary>
        Friend ReadOnly Property IrBusObj() As String
            Get
                Return ResourceManager.GetString("IrBusObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAlPrimero.
        '''</summary>
        Friend ReadOnly Property IrPriCmd() As String
            Get
                Return ResourceManager.GetString("IrPriCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ir Al Primero.
        '''</summary>
        Friend ReadOnly Property IrPriObj() As String
            Get
                Return ResourceManager.GetString("IrPriObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAlSiguiente.
        '''</summary>
        Friend ReadOnly Property IrSigCmd() As String
            Get
                Return ResourceManager.GetString("IrSigCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ir Al Siguiente.
        '''</summary>
        Friend ReadOnly Property IrSigObj() As String
            Get
                Return ResourceManager.GetString("IrSigObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdAlUltimo.
        '''</summary>
        Friend ReadOnly Property IrUltCmd() As String
            Get
                Return ResourceManager.GetString("IrUltCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ir Al Ultimo.
        '''</summary>
        Friend ReadOnly Property IrUltObj() As String
            Get
                Return ResourceManager.GetString("IrUltObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Licencia.
        '''</summary>
        Friend ReadOnly Property Licencia() As String
            Get
                Return ResourceManager.GetString("Licencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mascara Cuentas Contables.
        '''</summary>
        Friend ReadOnly Property MasCtasCont() As String
            Get
                Return ResourceManager.GetString("MasCtasCont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medio de Pago por defecto.
        '''</summary>
        Friend ReadOnly Property MedPagoDef() As String
            Get
                Return ResourceManager.GetString("MedPagoDef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta de cobro.
        '''</summary>
        Friend ReadOnly Property MenCtaCobro() As String
            Get
                Return ResourceManager.GetString("MenCtaCobro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Este es un correo de prueba enviado desde Orión.
        '''</summary>
        Friend ReadOnly Property MensPrueEmail() As String
            Get
                Return ResourceManager.GetString("MensPrueEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agregar _Sector Contribuyente.
        '''</summary>
        Friend ReadOnly Property MnuAgregarSectorModulo() As String
            Get
                Return ResourceManager.GetString("MnuAgregarSectorModulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdModificar.
        '''</summary>
        Friend ReadOnly Property ModCmd() As String
            Get
                Return ResourceManager.GetString("ModCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar un Objeto.
        '''</summary>
        Friend ReadOnly Property ModObj() As String
            Get
                Return ResourceManager.GetString("ModObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nota Aplicación Anticipo.
        '''</summary>
        Friend ReadOnly Property NAA() As String
            Get
                Return ResourceManager.GetString("NAA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nota Crédito.
        '''</summary>
        Friend ReadOnly Property NCR() As String
            Get
                Return ResourceManager.GetString("NCR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nota Intereses Mora.
        '''</summary>
        Friend ReadOnly Property NDB() As String
            Get
                Return ResourceManager.GetString("NDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;Ninguno&gt;.
        '''</summary>
        Friend ReadOnly Property Ninguno() As String
            Get
                Return ResourceManager.GetString("Ninguno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nivel de Captura de Ingresos.
        '''</summary>
        Friend ReadOnly Property NivCapturaIngresos() As String
            Get
                Return ResourceManager.GetString("NivCapturaIngresos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La presente Factura no Causa Mora.
        '''</summary>
        Friend ReadOnly Property NoCausa() As String
            Get
                Return ResourceManager.GetString("NoCausa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CONCEPTO DE FACTURACION.
        '''</summary>
        Friend ReadOnly Property NomAgrSer() As String
            Get
                Return ResourceManager.GetString("NomAgrSer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a AJUSTES CUOTA ADMINISTRACION.
        '''</summary>
        Friend ReadOnly Property NomAjuCtaAdm() As String
            Get
                Return ResourceManager.GetString("NomAjuCtaAdm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a AÑO.
        '''</summary>
        Friend ReadOnly Property NomAno() As String
            Get
                Return ResourceManager.GetString("NomAno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ANTICIPOS.
        '''</summary>
        Friend ReadOnly Property NomAnti() As String
            Get
                Return ResourceManager.GetString("NomAnti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a AUTORIZACION DESCUENTO.
        '''</summary>
        Friend ReadOnly Property NomAutDscto() As String
            Get
                Return ResourceManager.GetString("NomAutDscto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a AUXILIAR CONTABLE.
        '''</summary>
        Friend ReadOnly Property NomAuxCont() As String
            Get
                Return ResourceManager.GetString("NomAuxCont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a OrionPlusBk.
        '''</summary>
        Friend ReadOnly Property NombreBk() As String
            Get
                Return ResourceManager.GetString("NombreBk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre Carpeta.
        '''</summary>
        Friend ReadOnly Property NombreCarpeta() As String
            Get
                Return ResourceManager.GetString("NombreCarpeta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ServicioAno.
        '''</summary>
        Friend ReadOnly Property NombreNodoServicioAno() As String
            Get
                Return ResourceManager.GetString("NombreNodoServicioAno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Identificación del Predio.
        '''</summary>
        Friend ReadOnly Property NombrePredio() As String
            Get
                Return ResourceManager.GetString("NombrePredio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CAUSA INTERESES DE MORA.
        '''</summary>
        Friend ReadOnly Property NomCausaMora() As String
            Get
                Return ResourceManager.GetString("NomCausaMora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre Copropiedad.
        '''</summary>
        Friend ReadOnly Property NomCenUti() As String
            Get
                Return ResourceManager.GetString("NomCenUti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CONFIGURACION COPROPIEDAD.
        '''</summary>
        Friend ReadOnly Property NomCenUtilOri() As String
            Get
                Return ResourceManager.GetString("NomCenUtilOri", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CIERRA PERIODO ACTUAL.
        '''</summary>
        Friend ReadOnly Property NomCierraMes() As String
            Get
                Return ResourceManager.GetString("NomCierraMes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CLIENTES.
        '''</summary>
        Friend ReadOnly Property NomClientes() As String
            Get
                Return ResourceManager.GetString("NomClientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CUENTAS BANCOS.
        '''</summary>
        Friend ReadOnly Property NomCtaBco() As String
            Get
                Return ResourceManager.GetString("NomCtaBco", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CUENTAS CONTABILIDAD.
        '''</summary>
        Friend ReadOnly Property NomCtaCon() As String
            Get
                Return ResourceManager.GetString("NomCtaCon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuenta Correo Origen.
        '''</summary>
        Friend ReadOnly Property NomCtaCorreoOri() As String
            Get
                Return ResourceManager.GetString("NomCtaCorreoOri", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CUENTAS DE COBRO.
        '''</summary>
        Friend ReadOnly Property NomCtasCob() As String
            Get
                Return ResourceManager.GetString("NomCtasCob", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CORREO ELCTRONICO.
        '''</summary>
        Friend ReadOnly Property NomECorreo() As String
            Get
                Return ResourceManager.GetString("NomECorreo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACTURACION ELECTRONICA.
        '''</summary>
        Friend ReadOnly Property NomEFac() As String
            Get
                Return ResourceManager.GetString("NomEFac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTADO DE CUENTA.
        '''</summary>
        Friend ReadOnly Property NomEstaCta() As String
            Get
                Return ResourceManager.GetString("NomEstaCta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACTURA MANUAL.
        '''</summary>
        Friend ReadOnly Property NomFacMan() As String
            Get
                Return ResourceManager.GetString("NomFacMan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACTURAS.
        '''</summary>
        Friend ReadOnly Property NomFacts() As String
            Get
                Return ResourceManager.GetString("NomFacts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GENERAR FACTURAS.
        '''</summary>
        Friend ReadOnly Property NomGenFras() As String
            Get
                Return ResourceManager.GetString("NomGenFras", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GENERAR PREFACTURAS.
        '''</summary>
        Friend ReadOnly Property NomGenPreF() As String
            Get
                Return ResourceManager.GetString("NomGenPreF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IMPORTACIÓN.
        '''</summary>
        Friend ReadOnly Property NomImp() As String
            Get
                Return ResourceManager.GetString("NomImp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INFORME DE CONTINGENCIA.
        '''</summary>
        Friend ReadOnly Property NomInfCon() As String
            Get
                Return ResourceManager.GetString("NomInfCon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INTERFAZ CONTABLE.
        '''</summary>
        Friend ReadOnly Property NomIntCon() As String
            Get
                Return ResourceManager.GetString("NomIntCon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ORION PLUS: ACCESO Y REGISTRO.
        '''</summary>
        Friend ReadOnly Property NomLogOn() As String
            Get
                Return ResourceManager.GetString("NomLogOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODULOS DE CONTRIBICION.
        '''</summary>
        Friend ReadOnly Property NomModCont() As String
            Get
                Return ResourceManager.GetString("NomModCont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODULOS DEL SERVICIO.
        '''</summary>
        Friend ReadOnly Property NomModSer() As String
            Get
                Return ResourceManager.GetString("NomModSer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NOTAS AJUSTE CUOTA ADMIN..
        '''</summary>
        Friend ReadOnly Property NomNotAju() As String
            Get
                Return ResourceManager.GetString("NomNotAju", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NOTAS APLICACION ANTICIPOS .
        '''</summary>
        Friend ReadOnly Property NomNotAplAnt() As String
            Get
                Return ResourceManager.GetString("NomNotAplAnt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NOTAS CREDITO.
        '''</summary>
        Friend ReadOnly Property NomNotCr() As String
            Get
                Return ResourceManager.GetString("NomNotCr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NOTAS REINTEGRO ANTICIPOS.
        '''</summary>
        Friend ReadOnly Property NomNotDevAnt() As String
            Get
                Return ResourceManager.GetString("NomNotDevAnt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NOTAS INTERESES MORA.
        '''</summary>
        Friend ReadOnly Property NomNotInt() As String
            Get
                Return ResourceManager.GetString("NomNotInt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NOTAS REVERSION CREDITOS.
        '''</summary>
        Friend ReadOnly Property NomNotRevCr() As String
            Get
                Return ResourceManager.GetString("NomNotRevCr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CONFIGURAR APLICACION.
        '''</summary>
        Friend ReadOnly Property NomPara() As String
            Get
                Return ResourceManager.GetString("NomPara", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PREDIOS.
        '''</summary>
        Friend ReadOnly Property NomPre() As String
            Get
                Return ResourceManager.GetString("NomPre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PROGRAMACION FACTURAS.
        '''</summary>
        Friend ReadOnly Property NomProFact() As String
            Get
                Return ResourceManager.GetString("NomProFact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Propietario.
        '''</summary>
        Friend ReadOnly Property NomProp() As String
            Get
                Return ResourceManager.GetString("NomProp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RECIBOS DE CAJA.
        '''</summary>
        Friend ReadOnly Property NomRecCaj() As String
            Get
                Return ResourceManager.GetString("NomRecCaj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a REGISTRO LICENCIA APLICACION.
        '''</summary>
        Friend ReadOnly Property NomRegCla() As String
            Get
                Return ResourceManager.GetString("NomRegCla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre Representante Legal.
        '''</summary>
        Friend ReadOnly Property NomRepLeg() As String
            Get
                Return ResourceManager.GetString("NomRepLeg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a REVERSAR PREFACTURAS.
        '''</summary>
        Friend ReadOnly Property NomRevPreF() As String
            Get
                Return ResourceManager.GetString("NomRevPreF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SECTORES.
        '''</summary>
        Friend ReadOnly Property NomSec() As String
            Get
                Return ResourceManager.GetString("NomSec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SECTORES APORTAN AL MODULO.
        '''</summary>
        Friend ReadOnly Property NomSecMod() As String
            Get
                Return ResourceManager.GetString("NomSecMod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SERVICIO.
        '''</summary>
        Friend ReadOnly Property NomSer() As String
            Get
                Return ResourceManager.GetString("NomSer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a TASAS INTERESES DE MORA.
        '''</summary>
        Friend ReadOnly Property NomTasMor() As String
            Get
                Return ResourceManager.GetString("NomTasMor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre Tercero Copropiedad.
        '''</summary>
        Friend ReadOnly Property NomTerCenUti() As String
            Get
                Return ResourceManager.GetString("NomTerCenUti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a TERCERO ADMINISTRADOR.
        '''</summary>
        Friend ReadOnly Property NomTerceroAdmin() As String
            Get
                Return ResourceManager.GetString("NomTerceroAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a VENTANA PRINCIPAL.
        '''</summary>
        Friend ReadOnly Property NomVenMW() As String
            Get
                Return ResourceManager.GetString("NomVenMW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NOTAS CREDITO.
        '''</summary>
        Friend ReadOnly Property NotaCr() As String
            Get
                Return ResourceManager.GetString("NotaCr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nota Reversión Cr{edito Nro.
        '''</summary>
        Friend ReadOnly Property NotaRevRC() As String
            Get
                Return ResourceManager.GetString("NotaRevRC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Plazo por Defecto en Factura Manual.
        '''</summary>
        Friend ReadOnly Property PlazoFacManual() As String
            Get
                Return ResourceManager.GetString("PlazoFacManual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PREDIOS.
        '''</summary>
        Friend ReadOnly Property Predio() As String
            Get
                Return ResourceManager.GetString("Predio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Prefijo de Facturas.
        '''</summary>
        Friend ReadOnly Property PreFact() As String
            Get
                Return ResourceManager.GetString("PreFact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Prefijo de Notas de Contabilidad.
        '''</summary>
        Friend ReadOnly Property PreNoCo() As String
            Get
                Return ResourceManager.GetString("PreNoCo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Prefijo de Notas Crédito.
        '''</summary>
        Friend ReadOnly Property PreNoCr() As String
            Get
                Return ResourceManager.GetString("PreNoCr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Prefijo de Notas Débito.
        '''</summary>
        Friend ReadOnly Property PreNoDb() As String
            Get
                Return ResourceManager.GetString("PreNoDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Prefijo Nota Reversa Rec. Caja.
        '''</summary>
        Friend ReadOnly Property PreNotRevRC() As String
            Get
                Return ResourceManager.GetString("PreNotRevRC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Prefijo de las Prefacturas.
        '''</summary>
        Friend ReadOnly Property PrePrefact() As String
            Get
                Return ResourceManager.GetString("PrePrefact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Predios Procesados :.
        '''</summary>
        Friend ReadOnly Property PreProcesados() As String
            Get
                Return ResourceManager.GetString("PreProcesados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Prefijo de Recibos de Caja.
        '''</summary>
        Friend ReadOnly Property PreRec() As String
            Get
                Return ResourceManager.GetString("PreRec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Proceso cancelado por el Usuario!.
        '''</summary>
        Friend ReadOnly Property ProcesoCanc() As String
            Get
                Return ResourceManager.GetString("ProcesoCanc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Procesos Ejecutados: .
        '''</summary>
        Friend ReadOnly Property ProcesosEjec() As String
            Get
                Return ResourceManager.GetString("ProcesosEjec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Producto.
        '''</summary>
        Friend ReadOnly Property Producto() As String
            Get
                Return ResourceManager.GetString("Producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Proceso terminado.
        '''</summary>
        Friend ReadOnly Property ProTer() As String
            Get
                Return ResourceManager.GetString("ProTer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recibo de Caja.
        '''</summary>
        Friend ReadOnly Property RecCaja() As String
            Get
                Return ResourceManager.GetString("RecCaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recibos de Caja entre Fechas.
        '''</summary>
        Friend ReadOnly Property RecCajaFec() As String
            Get
                Return ResourceManager.GetString("RecCajaFec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdRefrescar.
        '''</summary>
        Friend ReadOnly Property RefCmd() As String
            Get
                Return ResourceManager.GetString("RefCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Refrescar un Objeto.
        '''</summary>
        Friend ReadOnly Property RefObj() As String
            Get
                Return ResourceManager.GetString("RefObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Registros Procesados:.
        '''</summary>
        Friend ReadOnly Property RegProcesados() As String
            Get
                Return ResourceManager.GetString("RegProcesados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Auxiliar Contable.
        '''</summary>
        Friend ReadOnly Property RepAuxiliarCon() As String
            Get
                Return ResourceManager.GetString("RepAuxiliarCon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Responsable: .
        '''</summary>
        Friend ReadOnly Property Respo() As String
            Get
                Return ResourceManager.GetString("Respo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reversando Pre-Facturas.
        '''</summary>
        Friend ReadOnly Property RevPreFac() As String
            Get
                Return ResourceManager.GetString("RevPreFac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sale de la Aplicación..
        '''</summary>
        Friend ReadOnly Property SaleApp() As String
            Get
                Return ResourceManager.GetString("SaleApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdSalirApp.
        '''</summary>
        Friend ReadOnly Property SaleAppCmd() As String
            Get
                Return ResourceManager.GetString("SaleAppCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  - .
        '''</summary>
        Friend ReadOnly Property Separador() As String
            Get
                Return ResourceManager.GetString("Separador", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Servicio.
        '''</summary>
        Friend ReadOnly Property Servicio() As String
            Get
                Return ResourceManager.GetString("Servicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Servicios Anuales.
        '''</summary>
        Friend ReadOnly Property ServiciosAnual() As String
            Get
                Return ResourceManager.GetString("ServiciosAnual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Servicios Permanentes.
        '''</summary>
        Friend ReadOnly Property ServiciosPerm() As String
            Get
                Return ResourceManager.GetString("ServiciosPerm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sin Información.
        '''</summary>
        Friend ReadOnly Property SinInfo() As String
            Get
                Return ResourceManager.GetString("SinInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No hay más Tareas para mostrar!.
        '''</summary>
        Friend ReadOnly Property SinTareas() As String
            Get
                Return ResourceManager.GetString("SinTareas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Solo comentario.
        '''</summary>
        Friend ReadOnly Property SolComen() As String
            Get
                Return ResourceManager.GetString("SolComen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Prueba Orión.
        '''</summary>
        Friend ReadOnly Property SubjeEmail() As String
            Get
                Return ResourceManager.GetString("SubjeEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a cmdSuprimir.
        '''</summary>
        Friend ReadOnly Property SupCmd() As String
            Get
                Return ResourceManager.GetString("SupCmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Suprimir un Objeto.
        '''</summary>
        Friend ReadOnly Property SupObj() As String
            Get
                Return ResourceManager.GetString("SupObj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tarea: .
        '''</summary>
        Friend ReadOnly Property Tarea() As String
            Get
                Return ResourceManager.GetString("Tarea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tasas Interés de Mora.
        '''</summary>
        Friend ReadOnly Property TasasMora() As String
            Get
                Return ResourceManager.GetString("TasasMora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tercero para las Cuentas de Caja y Bancos.
        '''</summary>
        Friend ReadOnly Property TerCtaCajaBancos() As String
            Get
                Return ResourceManager.GetString("TerCtaCajaBancos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Terminando Proceso.
        '''</summary>
        Friend ReadOnly Property TerPro() As String
            Get
                Return ResourceManager.GetString("TerPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Imagen(.jpg)|*.jpg.
        '''</summary>
        Friend ReadOnly Property TipoArchivoImagen() As String
            Get
                Return ResourceManager.GetString("TipoArchivoImagen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reporte(.rpt)|*.rpt.
        '''</summary>
        Friend ReadOnly Property TipoArchivoRep() As String
            Get
                Return ResourceManager.GetString("TipoArchivoRep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Archivo Excel (*.xls, *.xlsx)|*.xls;*.xlsx|Archivo Access (*.mdb)|*.mdb|Todos los archivos (*.*)|*.*.
        '''</summary>
        Friend ReadOnly Property TiposArchivosOrigen() As String
            Get
                Return ResourceManager.GetString("TiposArchivosOrigen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reporte: .
        '''</summary>
        Friend ReadOnly Property TituloRep() As String
            Get
                Return ResourceManager.GetString("TituloRep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;Todos&gt;.
        '''</summary>
        Friend ReadOnly Property Todos() As String
            Get
                Return ResourceManager.GetString("Todos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Total área de la copropiedad.
        '''</summary>
        Friend ReadOnly Property TotalAreaCoprop() As String
            Get
                Return ResourceManager.GetString("TotalAreaCoprop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Total área ponderada.
        '''</summary>
        Friend ReadOnly Property TotalAreaPond() As String
            Get
                Return ResourceManager.GetString("TotalAreaPond", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Total unidades del sector.
        '''</summary>
        Friend ReadOnly Property TotalUnidadesSector() As String
            Get
                Return ResourceManager.GetString("TotalUnidadesSector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre la Ventana de los Módulo que contribuyen al Servicio.
        '''</summary>
        Friend ReadOnly Property TTAbrirModulosServicio() As String
            Get
                Return ResourceManager.GetString("TTAbrirModulosServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abre la Ventana de los Sectores que Contribuyen al Servicio.
        '''</summary>
        Friend ReadOnly Property TTAbrirSectoresServicio() As String
            Get
                Return ResourceManager.GetString("TTAbrirSectoresServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Adiciona un Modulo de Contribución al Servicio.
        '''</summary>
        Friend ReadOnly Property TTAdicionaModuloServicio() As String
            Get
                Return ResourceManager.GetString("TTAdicionaModuloServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agrega un Sector para contribuir con el Modulo Actual.
        '''</summary>
        Friend ReadOnly Property TTAgreSecMod() As String
            Get
                Return ResourceManager.GetString("TTAgreSecMod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agrega todos los Sector para contribuir con el Modulo Actual.
        '''</summary>
        Friend ReadOnly Property TTAgreTodosSecMod() As String
            Get
                Return ResourceManager.GetString("TTAgreTodosSecMod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dar clic contrario para abrir la ventana &apos;Conceptos de Facturación&apos;.
        '''</summary>
        Friend ReadOnly Property TTAgruServicios() As String
            Get
                Return ResourceManager.GetString("TTAgruServicios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Total del área o de las unidades que conforman el Sector.
        '''</summary>
        Friend ReadOnly Property TTBaseSector() As String
            Get
                Return ResourceManager.GetString("TTBaseSector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Con Ctrl+F2 se muestra el Panel Siguiente; Con Ctrl+F3 se muestra el Panel Anterior.
        '''</summary>
        Friend ReadOnly Property TTBotonesDePanel() As String
            Get
                Return ResourceManager.GetString("TTBotonesDePanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancela el Reporte y Cierra la Ventana.
        '''</summary>
        Friend ReadOnly Property TTCierraVen() As String
            Get
                Return ResourceManager.GetString("TTCierraVen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dar clic contrario o doble clic para configurar la Copropiedad.
        '''</summary>
        Friend ReadOnly Property TTConfiguracion() As String
            Get
                Return ResourceManager.GetString("TTConfiguracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estando habilitado genera el Reporte.
        '''</summary>
        Friend ReadOnly Property TTGeneraRep() As String
            Get
                Return ResourceManager.GetString("TTGeneraRep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dar clic contrario para abrir la ventana &apos;Cuentas Contabilidad&apos;.
        '''</summary>
        Friend ReadOnly Property TTPlanContable() As String
            Get
                Return ResourceManager.GetString("TTPlanContable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 1=No se redondea; de 4 a 9: Se redondea a la cantidad de decimales indicado..
        '''</summary>
        Friend ReadOnly Property TTRedoCP() As String
            Get
                Return ResourceManager.GetString("TTRedoCP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Los intereses por mora y los descuentos por pronto pago se redondean asi: .
        '''</summary>
        Friend ReadOnly Property TTRedoIM() As String
            Get
                Return ResourceManager.GetString("TTRedoIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.1=Redondea a décimo; 0.2=Redondea a centecimos; Número Entero=Redondea a multiplo entero del número..
        '''</summary>
        Friend ReadOnly Property TTRedoOpeMonet() As String
            Get
                Return ResourceManager.GetString("TTRedoOpeMonet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dar clic contrario para seleccionar la acción a ejecutar.
        '''</summary>
        Friend ReadOnly Property TTSeleccionarAccion() As String
            Get
                Return ResourceManager.GetString("TTSeleccionarAccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dar clic contrario para abrir la ventana &apos;Servicios&apos;.
        '''</summary>
        Friend ReadOnly Property TTServicio() As String
            Get
                Return ResourceManager.GetString("TTServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario: .
        '''</summary>
        Friend ReadOnly Property Usuario() As String
            Get
                Return ResourceManager.GetString("Usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Versión.
        '''</summary>
        Friend ReadOnly Property Ver() As String
            Get
                Return ResourceManager.GetString("Ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Windows.
        '''</summary>
        Friend ReadOnly Property Windows() As String
            Get
                Return ResourceManager.GetString("Windows", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
