name: ci

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: nuget restore .\OrionCop.Net.sln

      - name: Build
        run: msbuild .\OrionCop.Net.sln /p:Configuration=Release /p:Platform=x64 /m

      - name: Upload OrionPlus artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrionPlus-native-x64
          path: .\build\releases\orion-plus\**
